### PR TITLE
fix: allow string array as keys option

### PR DESCRIPTION
**Pull request by Uzlopak**
According to the readme and the overall implementation it should be possible to pass an array. But typescript types dont allow. Also hardening against errors.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Can you resolve the conflicts?

**Comment by Uzlopak** [comment]
@mcollina 

Done.

**Review by gurgunday — APPROVED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
