### PR TITLE
fix: Use @fastify/error to create errors

### LINKED ISSUE #178: Use @fastify/error to create errors
Use @fastify/error to create errors `FST_BEARER_AUTH_MISSING_AUTHORIZATION_HEADER` and `FST_BEARER_AUTH_INVALID_AUTHORIZATION_HEADER`
> Should we use @fastify/error to create FST_BEARER_AUTH_MISSING_AUTHORIZATION_HEADER and FST_BEARER_AUTH_INVALID_AUTHORIZATION_HEADER  and use that instead? Would also be better passing them to the callback instead of native Node Errors?

_Originally posted by @Uzlopak in https://github.com/fastify/fastify-bearer-auth/issues/167#issuecomment-1870367425_

### PR DESCRIPTION
**Pull request by dancastillo**
Work done: Use @fastify/error to create errors FST_BEARER_AUTH_MISSING_AUTH…ORIZATION_HEADER and FST_BEARER_AUTH_INVALID_AUTHORIZATION_HEADER
Closes: #178 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by gurgunday — APPROVED** [review]
lgtm, should we capitalize the messages or is it fine?

https://github.com/fastify/fastify-bearer-auth/pull/179/files#diff-0af7067b49efcaf7dae9a3707f2e79638b336e72780d2b834e007f80ef9a5fa0R9-R10

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Uzlopak** [comment]
> lgtm, should we capitalize the messages or is it fine?
> 
> https://github.com/fastify/fastify-bearer-auth/pull/179/files#diff-0af7067b49efcaf7dae9a3707f2e79638b336e72780d2b834e007f80ef9a5fa0R9-R10

image

**Review by Uzlopak — APPROVED** [review]
LGTM

**Pull request merged**
