### PR TITLE
Improve performance, fix bug in authorization schema

### PR DESCRIPTION
**Pull request by Uzlopak**
While programming I realized we have a bug in the code. We did not check if between `Bearer`and key was atleast one space. This bug is fixed, see unit tests.

before:
Missing Header:
```sh
autocannon http://127.0.0.1:8000/foo
0 2xx responses, 271167 non 2xx responses
271k requests in 10.01s, 59.9 MB read
```

Invalid BearerType:
```sh
autocannon -H authorization='Beaver key' http://127.0.0.1:8000/foo
0 2xx responses, 295334 non 2xx responses
295k requests in 11.01s, 65.3 MB read
```

Invalid key:
```sh
autocannon -H authorization='Bearer invalid' http://127.0.0.1:8000/foo
0 2xx responses, 274488 non 2xx responses
274k requests in 11.01s, 60.7 MB read
```

Valid Request:
```sh
autocannon -H authorization='Bearer key' http://127.0.0.1:8000/foo
272k requests in 11.01s, 52.6 MB read
```

after:
Missing Header:
```sh
autocannon http://127.0.0.1:8000/foo
0 2xx responses, 300072 non 2xx responses
300k requests in 11.01s, 66.3 MB read
```

Invalid BearerType:
```sh
autocannon -H authorization='Beaver key' http://127.0.0.1:8000/foo
0 2xx responses, 291809 non 2xx responses
292k requests in 11.01s, 64.5 MB read
```

Invalid key:
```sh
autocannon -H authorization='Bearer invalid' http://127.0.0.1:8000/foo
0 2xx responses, 326559 non 2xx responses
327k requests in 11.01s, 72.2 MB read
```

Valid Request:
```sh
autocannon -H authorization='Bearer key' http://127.0.0.1:8000/foo
404k requests in 11.01s, 77.9 MB read
```

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by gurgunday — APPROVED** [review]
Looks great!

**Review by Eomm — APPROVED** [review]

**Comment by olivierchatry** [comment]
I'm quite sure that BearerType should be case insensitive.

**Comment by Uzlopak** [comment]
@olivierchatry 

My PR did not change any behaviour regarding case sensitivity. Probably you wanted to comment it on PR #167 by @dancastillo , who changed `bearer` to `Bearer`. 

Eitherway, maybe open an issue to discuss it.

**Comment by jsumners** [comment]
I am quite certain the spec requires `Bearer` https://www.rfc-editor.org/rfc/rfc6750#section-2.1

**Comment by olivierchatry** [comment]
https://github.com/lexik/LexikJWTAuthenticationBundle/issues/411

I think this is just a string comparaison, and there will most probably be bearer and Bearer in the wilde. This is really just string comparison, so I'm not sure why not do it.

**Comment by Uzlopak** [comment]
@olivierchatry 

Please open an issue and discuss this there. Please also refer also to RFCs. This PR did not change that behaviour as I already explained.

**Pull request merged**
